### ISSUE TITLE
Directory is not empty

### ISSUE THREAD

**Issue by superlou** [ankushshah89/python-docx2txt#1]
I am intermittently getting errors saying the directory is not empty:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\_PROJECTS\doc_ref\tests\test_docx_parsing.py", line 11, in test_handle_tracked_changes
    document = SafeFlightDoc('tests/docs/test_tracked_changes.docx')
  File "C:\_PROJECTS\doc_ref\doc_ref\safe_flight_doc.py", line 15, in __init__
    self.text = docx2txt.process(self.filename)
  File "C:\Python27\lib\site-packages\docx2txt\docx2txt.py", line 73, in process
    shutil.rmtree(temp_dir)
  File "C:\Python27\lib\shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 254, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 252, in rmtree
    os.rmdir(path)
WindowsError: [Error 145] The directory is not empty: 'c:\\users\\lsimons\\appdata\\local\\temp\\tmphlcb12\\docProps'
```

I am on Windows with Python 2.7 32-bit with the latest docx2txt installed via pip.  This is intermittent.   Sometimes it runs successfully.

**Comment by ankushshah89** [comment]
thanks for reporting @superlou . I checked the problem and it's an issue with shutil.rmtree() on windows. I think its unable to delete temp files because of cache/latency. A quick workaround would be to change the line 73 in the file C:\Python27\lib\site-packages\docx2txt\docx2txt.py 

from
```python
shutil.rmtree(temp_dir)
```
to
```python
shutil.rmtree(temp_dir, ignore_errors=True)
```

This would just suppress the error but still won't be deleting the temporary directory created by the docx2txt. So, in the end you might see some temporary directories.

**Comment by ankushshah89** [comment]
This issue is [fixed](https://github.com/ankushshah89/python-docx2txt/commit/353ca4621ee371074f8e2c2025c00d8327135504) in the latest version by removing dependency on shutil.rmtree(). Please update to version 0.4

**Comment by superlou** [comment]
That fixed it.  Thanks!
